name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zig
        run: |
          sudo snap install zig --classic --edge
          zig version

      - run: zig build test
      - run: zig build -Doptimize=ReleaseFast

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zig
        run: |
          sudo snap install zig --classic --edge
          zig version

      - run: zig build -Doptimize=ReleaseFast